/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/auth/layout'
import { Route as WwwLayoutRouteImport } from './pages/_www/layout'
import { Route as ProtectedLayoutRouteImport } from './pages/_protected/layout'
import { Route as WwwIndexRouteImport } from './pages/_www/index'
import { Route as AuthRegisterRouteImport } from './pages/auth/register'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as ProtectedUserLayoutRouteImport } from './pages/_protected/$user/layout'
import { Route as ProtectedUserIndexRouteImport } from './pages/_protected/$user/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WwwLayoutRoute = WwwLayoutRouteImport.update({
  id: '/_www',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const WwwIndexRoute = WwwIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WwwLayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ProtectedUserLayoutRoute = ProtectedUserLayoutRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedUserIndexRoute = ProtectedUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedUserLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/$user': typeof ProtectedUserLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof WwwIndexRoute
  '/$user/': typeof ProtectedUserIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof WwwIndexRoute
  '/$user': typeof ProtectedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_www': typeof WwwLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_protected/$user': typeof ProtectedUserLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_www/': typeof WwwIndexRoute
  '/_protected/$user/': typeof ProtectedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/$user'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/$user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/auth/login' | '/auth/register' | '/' | '/$user'
  id:
    | '__root__'
    | '/_protected'
    | '/_www'
    | '/auth'
    | '/_protected/$user'
    | '/auth/login'
    | '/auth/register'
    | '/_www/'
    | '/_protected/$user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  WwwLayoutRoute: typeof WwwLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_www': {
      id: '/_www'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WwwLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_www/': {
      id: '/_www/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WwwIndexRouteImport
      parentRoute: typeof WwwLayoutRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_protected/$user': {
      id: '/_protected/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof ProtectedUserLayoutRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/$user/': {
      id: '/_protected/$user/'
      path: '/'
      fullPath: '/$user/'
      preLoaderRoute: typeof ProtectedUserIndexRouteImport
      parentRoute: typeof ProtectedUserLayoutRoute
    }
  }
}

interface ProtectedUserLayoutRouteChildren {
  ProtectedUserIndexRoute: typeof ProtectedUserIndexRoute
}

const ProtectedUserLayoutRouteChildren: ProtectedUserLayoutRouteChildren = {
  ProtectedUserIndexRoute: ProtectedUserIndexRoute,
}

const ProtectedUserLayoutRouteWithChildren =
  ProtectedUserLayoutRoute._addFileChildren(ProtectedUserLayoutRouteChildren)

interface ProtectedLayoutRouteChildren {
  ProtectedUserLayoutRoute: typeof ProtectedUserLayoutRouteWithChildren
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedUserLayoutRoute: ProtectedUserLayoutRouteWithChildren,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface WwwLayoutRouteChildren {
  WwwIndexRoute: typeof WwwIndexRoute
}

const WwwLayoutRouteChildren: WwwLayoutRouteChildren = {
  WwwIndexRoute: WwwIndexRoute,
}

const WwwLayoutRouteWithChildren = WwwLayoutRoute._addFileChildren(
  WwwLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  WwwLayoutRoute: WwwLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
