/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/auth/layout'
import { Route as ProtectedLayoutRouteImport } from './pages/_protected/layout'
import { Route as ProtectedIndexRouteImport } from './pages/_protected/index'
import { Route as AuthRegisterIndexRouteImport } from './pages/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './pages/auth/login/index'
import { Route as ProtectedTasksIndexRouteImport } from './pages/_protected/tasks/index'
import { Route as ProtectedResourceIndexRouteImport } from './pages/_protected/resource/index'
import { Route as AuthPasswordForgotRouteImport } from './pages/auth/password/forgot'
import { Route as ProtectedTasksWorkflowRouteImport } from './pages/_protected/tasks/workflow'
import { Route as ProtectedTasksTaskIdRouteImport } from './pages/_protected/tasks/$taskId'
import { Route as ProtectedCNewRouteImport } from './pages/_protected/c/new'
import { Route as ProtectedCSlugRouteImport } from './pages/_protected/c/$slug'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ProtectedTasksIndexRoute = ProtectedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedResourceIndexRoute = ProtectedResourceIndexRouteImport.update({
  id: '/resource/',
  path: '/resource/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const AuthPasswordForgotRoute = AuthPasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ProtectedTasksWorkflowRoute = ProtectedTasksWorkflowRouteImport.update({
  id: '/tasks/workflow',
  path: '/tasks/workflow',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedTasksTaskIdRoute = ProtectedTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedCNewRoute = ProtectedCNewRouteImport.update({
  id: '/c/new',
  path: '/c/new',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedCSlugRoute = ProtectedCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/c/$slug': typeof ProtectedCSlugRoute
  '/c/new': typeof ProtectedCNewRoute
  '/tasks/$taskId': typeof ProtectedTasksTaskIdRoute
  '/tasks/workflow': typeof ProtectedTasksWorkflowRoute
  '/auth/password/forgot': typeof AuthPasswordForgotRoute
  '/resource': typeof ProtectedResourceIndexRoute
  '/tasks': typeof ProtectedTasksIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/c/$slug': typeof ProtectedCSlugRoute
  '/c/new': typeof ProtectedCNewRoute
  '/tasks/$taskId': typeof ProtectedTasksTaskIdRoute
  '/tasks/workflow': typeof ProtectedTasksWorkflowRoute
  '/auth/password/forgot': typeof AuthPasswordForgotRoute
  '/resource': typeof ProtectedResourceIndexRoute
  '/tasks': typeof ProtectedTasksIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/c/$slug': typeof ProtectedCSlugRoute
  '/_protected/c/new': typeof ProtectedCNewRoute
  '/_protected/tasks/$taskId': typeof ProtectedTasksTaskIdRoute
  '/_protected/tasks/workflow': typeof ProtectedTasksWorkflowRoute
  '/auth/password/forgot': typeof AuthPasswordForgotRoute
  '/_protected/resource/': typeof ProtectedResourceIndexRoute
  '/_protected/tasks/': typeof ProtectedTasksIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/c/$slug'
    | '/c/new'
    | '/tasks/$taskId'
    | '/tasks/workflow'
    | '/auth/password/forgot'
    | '/resource'
    | '/tasks'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/c/$slug'
    | '/c/new'
    | '/tasks/$taskId'
    | '/tasks/workflow'
    | '/auth/password/forgot'
    | '/resource'
    | '/tasks'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/'
    | '/_protected/c/$slug'
    | '/_protected/c/new'
    | '/_protected/tasks/$taskId'
    | '/_protected/tasks/workflow'
    | '/auth/password/forgot'
    | '/_protected/resource/'
    | '/_protected/tasks/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_protected/tasks/': {
      id: '/_protected/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ProtectedTasksIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/resource/': {
      id: '/_protected/resource/'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof ProtectedResourceIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/auth/password/forgot': {
      id: '/auth/password/forgot'
      path: '/password/forgot'
      fullPath: '/auth/password/forgot'
      preLoaderRoute: typeof AuthPasswordForgotRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_protected/tasks/workflow': {
      id: '/_protected/tasks/workflow'
      path: '/tasks/workflow'
      fullPath: '/tasks/workflow'
      preLoaderRoute: typeof ProtectedTasksWorkflowRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/tasks/$taskId': {
      id: '/_protected/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof ProtectedTasksTaskIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/c/new': {
      id: '/_protected/c/new'
      path: '/c/new'
      fullPath: '/c/new'
      preLoaderRoute: typeof ProtectedCNewRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/c/$slug': {
      id: '/_protected/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof ProtectedCSlugRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedCSlugRoute: typeof ProtectedCSlugRoute
  ProtectedCNewRoute: typeof ProtectedCNewRoute
  ProtectedTasksTaskIdRoute: typeof ProtectedTasksTaskIdRoute
  ProtectedTasksWorkflowRoute: typeof ProtectedTasksWorkflowRoute
  ProtectedResourceIndexRoute: typeof ProtectedResourceIndexRoute
  ProtectedTasksIndexRoute: typeof ProtectedTasksIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedCSlugRoute: ProtectedCSlugRoute,
  ProtectedCNewRoute: ProtectedCNewRoute,
  ProtectedTasksTaskIdRoute: ProtectedTasksTaskIdRoute,
  ProtectedTasksWorkflowRoute: ProtectedTasksWorkflowRoute,
  ProtectedResourceIndexRoute: ProtectedResourceIndexRoute,
  ProtectedTasksIndexRoute: ProtectedTasksIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
